spring:
  application:
    name: Rootin

# OpenAI API 설정
openai:
  api-key: ${OPENAI_API_KEY:dummy}
  model: ${OPENAI_MODEL:gpt-5.4-nano}
  summary:
    max-tokens: ${OPENAI_SUMMARY_MAX_TOKENS:500}
  quiz:
    max-tokens: ${OPENAI_QUIZ_MAX_TOKENS:1000}

jwt:
  secret: c2lsdmVyLWJlbGwtc2VjcmV0LWtleS1mb3Itc3ByaW5nLWJvb3Qtand0LXR1dG9yaWFs
  access-token-expiration: 1800000      # 30분
  refresh-token-expiration: 1209600000  # 14일

# AWS S3 설정
cloud:
  aws:
    region: ${AWS_REGION:ap-northeast-2}
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID:dummy}
      secret-key: ${AWS_SECRET_ACCESS_KEY:dummy}
    s3:
      bucket: ${AWS_S3_BUCKET:demo}
      endpoint: ${AWS_ENDPOINT:}


# Actuator (Docker Health)
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

---
# Local에서 테스트 겸 자유롭게 돌려도 되는 DB 설정
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/rootin?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: "1234"
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: tr
        jdbc:
          time_zone: Asia/Seoul

---
# 실제 서비스 서버에서 사용하는 DB 설정
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:rootin}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul

